name: Run API Pipeline Tests

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pytest-html allure-pytest

    - name: Run Pytest with HTML & Allure Report
      run: |
        mkdir -p reports/pytest-html-reports
        mkdir -p reports/allure-reports
        pytest tests/ --html=reports/pytest-html-reports/report.html --self-contained-html --alluredir=reports/allure-reports/

    - name: Generate Allure report
      run: |
        npm install -g allure-commandline --save-dev
        allure generate reports/allure-reports -o reports/allure-reports/html --clean

    - name: Upload HTML report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: pytest-html-report
        path: reports/pytest-html-reports/html-report.html

    - name: Upload Allure HTML report artifact
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: allure-html-report
        path: reports/allure-reports/html/
